name: figlet-workflow

on:
  workflow_dispatch:
    inputs:
      text:
        required: true
        default: Hello, World!


jobs:
  figlet-job:
    runs-on: ubuntu-latest
    steps:
      - name: figlet-step
        uses: yuji314159/figlet-action@main
        with:
          text: ${{ inputs.text }}
